[32m2025-06-16 14:28:21 +0800[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - 4e8ca69f-a3d2-42ba-be72-ba747be7b70a - 43821 - LOGS_CAPTURED - Started capturing logs in process (pid: 43821).
[32m2025-06-16 14:28:21 +0800[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - 4e8ca69f-a3d2-42ba-be72-ba747be7b70a - 43821 - processed_kaggle_data - STEP_START - Started execution of step "processed_kaggle_data".
[32m2025-06-16 14:28:21 +0800[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - 4e8ca69f-a3d2-42ba-be72-ba747be7b70a - processed_kaggle_data - Loading file from: /Users/taysk/sctp/Project/SCTP-DSF1-Team5/03 - Code/pipeline-olist/pipeline_olist/data/kaggle_dataset using PickledObjectFilesystemIOManager...
[32m2025-06-16 14:28:21 +0800[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - 4e8ca69f-a3d2-42ba-be72-ba747be7b70a - 43821 - processed_kaggle_data - LOADED_INPUT - Loaded input "kaggle_dataset" using input manager "io_manager"
[32m2025-06-16 14:28:21 +0800[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - 4e8ca69f-a3d2-42ba-be72-ba747be7b70a - 43821 - processed_kaggle_data - STEP_INPUT - Got input "kaggle_dataset" of type "Path". (Type check passed).
[32m2025-06-16 14:28:21 +0800[0m - dagster - [34mERROR[0m - [31m__ASSET_JOB - 4e8ca69f-a3d2-42ba-be72-ba747be7b70a - 43821 - processed_kaggle_data - STEP_FAILURE - Execution of step "processed_kaggle_data" failed.

dagster._core.errors.DagsterExecutionStepExecutionError: Error occurred while executing op "processed_kaggle_data"::

AttributeError: 'str' object has no attribute 'glob'

Stack Trace:
  File "/opt/anaconda3/envs/elt/lib/python3.10/site-packages/dagster/_core/execution/plan/utils.py", line 56, in op_execution_error_boundary
    yield
  File "/opt/anaconda3/envs/elt/lib/python3.10/site-packages/dagster/_utils/__init__.py", line 392, in iterate_with_context
    next_output = next(iterator)
  File "/opt/anaconda3/envs/elt/lib/python3.10/site-packages/dagster/_core/execution/plan/compute_generator.py", line 129, in _coerce_op_compute_fn_to_iterator
    result = invoke_compute_fn(
  File "/opt/anaconda3/envs/elt/lib/python3.10/site-packages/dagster/_core/execution/plan/compute_generator.py", line 117, in invoke_compute_fn
    return fn(context, **args_to_pass) if context_arg_provided else fn(**args_to_pass)
  File "/Users/taysk/sctp/Project/SCTP-DSF1-Team5/03 - Code/pipeline-olist/pipeline_olist/assets.py", line 101, in processed_kaggle_data
    csv_files = list(kaggle_dataset.glob("*.csv"))
[0m
